name: ui_task
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.1.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1
  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  shared_code:
    git: 
      url: https://github.com/amrmhassan/shiaka_shared_code.git
      ref: main
  reaya_shared_code:
    git: 
      url: https://github.com/amrmhassan/reaya_shared_code.git
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/categories/
    - assets/nav/
